import { http } from "../utils/http";

// import qs from 'qs'

// 获取地图配置信息
export const getMapConfig = (): any => {
  return Promise.resolve({
    code: 1,
    msg: "",
    time: "1758676218",
    data: [
      {
        id: 41,
        name: "baseLayerPicker",
        group: "map_config",
        title: "基础影响图层选择器",
        tip: "",
        type: "switch",
        value: "0",
        content: "",
        rule: "",
        extend: "",
      },
      {
        id: 42,
        name: "navigationHelpButton",
        group: "map_config",
        title: "导航帮助按钮",
        tip: "",
        type: "switch",
        value: "0",
        content: "",
        rule: "",
        extend: "",
      },
      {
        id: 43,
        name: "animation",
        group: "map_config",
        title: "动画控件",
        tip: "",
        type: "switch",
        value: "0",
        content: "",
        rule: "",
        extend: "",
      },
      {
        id: 44,
        name: "timeline",
        group: "map_config",
        title: "时间控件",
        tip: "",
        type: "switch",
        value: "0",
        content: "",
        rule: "",
        extend: "",
      },
      {
        id: 45,
        name: "shadows",
        group: "map_config",
        title: "显示阴影",
        tip: "",
        type: "switch",
        value: "0",
        content: "",
        rule: "",
        extend: "",
      },
      {
        id: 46,
        name: "shouldAnimate",
        group: "map_config",
        title: "大气模型动画效果",
        tip: "",
        type: "switch",
        value: "1",
        content: "",
        rule: "",
        extend: "",
      },
      {
        id: 47,
        name: "skyBox",
        group: "map_config",
        title: "天空盒",
        tip: "",
        type: "switch",
        value: "0",
        content: "",
        rule: "",
        extend: "",
      },
      {
        id: 48,
        name: "infoBox",
        group: "map_config",
        title: "信息提示框",
        tip: "",
        type: "switch",
        value: "0",
        content: "",
        rule: "",
        extend: "",
      },
      {
        id: 49,
        name: "fullscreenButton",
        group: "map_config",
        title: "是否显示全屏按钮",
        tip: "",
        type: "switch",
        value: "0",
        content: "",
        rule: "",
        extend: "",
      },
      {
        id: 50,
        name: "logo",
        group: "map_config",
        title: "显示cesiumLogo",
        tip: "",
        type: "switch",
        value: "0",
        content: "",
        rule: "",
        extend: "",
      },
      {
        id: 51,
        name: "homeButton",
        group: "map_config",
        title: "首页按钮",
        tip: "",
        type: "switch",
        value: "0",
        content: "",
        rule: "",
        extend: "",
      },
      {
        id: 52,
        name: "sceneModePicker",
        group: "map_config",
        title: "展示视角切换按钮",
        tip: "",
        type: "switch",
        value: "1",
        content: "",
        rule: "",
        extend: "",
      },
      {
        id: 66,
        name: "frontDebugger",
        group: "map_config",
        title: "是否为前端调试模式",
        tip: "",
        type: "switch",
        value: "0",
        content: "",
        rule: "",
        extend: "",
      },
    ],
  });
};

// 获取地图初始化视角
export const getMapView = (): any => {
  return Promise.resolve({
    code: 1,
    msg: "",
    time: "1758677065",
    data: [
      {
        id: 53,
        name: "showSaveButton",
        group: "map_view_first",
        title: "显示保存当前摄像头视角按钮",
        tip: "",
        type: "switch",
        value: "0",
        content: "",
        rule: "",
        extend: "",
      },
      {
        id: 54,
        name: "lat",
        group: "map_view_first",
        title: "初始化经度",
        tip: "",
        type: "string",
        value: "22.517498452006",
        content: "",
        rule: "",
        extend: "",
      },
      {
        id: 55,
        name: "lng",
        group: "map_view_first",
        title: "初始化纬度",
        tip: "",
        type: "string",
        value: "113.94841594169",
        content: "",
        rule: "",
        extend: "",
      },
      {
        id: 56,
        name: "height",
        group: "map_view_first",
        title: "初始化高度",
        tip: "",
        type: "string",
        value: "1886.2633663497",
        content: "",
        rule: "",
        extend: "",
      },
      {
        id: 57,
        name: "direction_x",
        group: "map_view_first",
        title: "摄像头方向direction_x",
        tip: "",
        type: "string",
        value: "0.31630848031566",
        content: "",
        rule: "",
        extend: "",
      },
      {
        id: 58,
        name: "direction_y",
        group: "map_view_first",
        title: "摄像头方向direction_y",
        tip: "",
        type: "string",
        value: "-0.71216534848501",
        content: "",
        rule: "",
        extend: "",
      },
      {
        id: 59,
        name: "direction_z",
        group: "map_view_first",
        title: "摄像头方向direction_z",
        tip: "",
        type: "string",
        value: "0.62671322125644",
        content: "",
        rule: "",
        extend: "",
      },
      {
        id: 60,
        name: "up_x",
        group: "map_view_first",
        title: "摄像头up_x",
        tip: "",
        type: "string",
        value: "-0.25439167219647",
        content: "",
        rule: "",
        extend: "",
      },
      {
        id: 61,
        name: "up_y",
        group: "map_view_first",
        title: "摄像头up_y",
        tip: "",
        type: "string",
        value: "0.57276028040945",
        content: "",
        rule: "",
        extend: "",
      },
      {
        id: 62,
        name: "up_z",
        group: "map_view_first",
        title: "摄像头up_z",
        tip: "",
        type: "string",
        value: "0.77924998447378",
        content: "",
        rule: "",
        extend: "",
      },
      {
        id: 63,
        name: "duration",
        group: "map_view_first",
        title: "飞跃延迟时间",
        tip: "单位（秒）",
        type: "string",
        value: "1",
        content: "",
        rule: "",
        extend: "",
      },
      {
        id: 65,
        name: "flytoView",
        group: "map_view_first",
        title: "是否飞到视图",
        tip: "",
        type: "switch",
        value: "1",
        content: "",
        rule: "",
        extend: "",
      },
    ],
  });
};

// 获取底图层级list
export const getMapImageryList = (): any => {
  return Promise.resolve({
    "code": 1,
    "msg": "",
    "time": "1758714740",
    "data": [
        {
            "id": 14,
            "name": "高德地图01",
            "type": "UrlTemplateImageryProvider",
            "classConfig": "{\"url\":\"http:\/\/webst03.is.autonavi.com\/appmaptile?x={x}&y={y}&z={z}&style=7\"}",
            "interfaceConfig": "{\"saturation\":\"0.0\",\"brightness\":\"0.6\",\"contrast\":\"1.8\",\"hue\":\"1\",\"gamma\":\"0.3\"}",
            "offset": "0,0",
            "invertswitch": 1,
            "filterRGB": "#4e70a6",
            "showswitch": 1,
            "weigh": 2,
            "createtime": 1624326728,
            "updatetime": 1646979297
        }
    ]
})
};

// 设置地图初始化视角
export const setMapView = (data: any): any => {
  return http.post("/base/setMapView", data);
};
